dist: trusty
sudo: false

language: python

python:
  - 3.5

install:
  - pip install codecov
  - pip install coverage
  - pip install setuptools
  - /bin/bash -c "source ~/virtualenv/python3.5/bin/activate && git clone https://github.com/SecuredByTHEM/ndr-netcfg.git && cd ndr-netcfg && ./setup.py install"

script:
  - coverage run --source=ndr setup.py test
#  - python3 setup.py test

after_success:
  - codecov

