dist: trusty
sudo: false

language: python

python:
  - 3.5

install:
  - pip install codecov
  - pip install coverage
  - pip install git+https://github.com/SecuredByTHEM/ndr-netcfg.git

script:
  - coverage run --source=ndr setup.py test
#  - python3 setup.py test

after_success:
  - codecov

