sudo: false

language: python

python:
  - 3.5

install:
  - pip install codecov
  - pip install pyyaml
  - pip install cryptography

script:
  - coverage run --source=ndr setup.py test

after_success:
  - codecov

