dist: trusty
sudo: true

language: python

python:
  - 3.5

install:
  - sudo apt-get -y build-dep wireshark
  - git clone https://github.com/SecuredByTHEM/wireshark.git -b ndr_tshark
  - cd wireshark && ./autogen.sh && ./configure --prefix=/opt/tshark-ndr/ && make && make install && cd ..
  - pip install codecov
  - pip install coverage
  - pip install git+https://github.com/SecuredByTHEM/ndr-netcfg.git

script:
  - coverage run --source=ndr setup.py test
#  - python3 setup.py test

after_success:
  - codecov

